# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Fluxion desktop app (slim build).

Bundles the GUI + chat + agent + license stack + RAG store (chromadb).
Embeddings run via the Ollama server (/api/embed, model bge-m3), so
torch/sentence-transformers are NOT bundled. Remaining optional deps
(flashrank, trafilatura, tree-sitter) degrade gracefully.
"""
import os

block_cipher = None

a = Analysis(
    ["run_desktop.py"],
    pathex=[os.path.abspath(".")],
    binaries=[],
    datas=[
        ("assets", "assets"),
        ("config", "config"),
        ("finetune", "finetune"),
        ("licensing", "licensing"),
    ],
    hiddenimports=[
        "desktop",
        "desktop.app",
        "desktop.engine",
        "desktop.license_dialog",
        "desktop.training",
        "finetune",
        "finetune.qlora_config",
        "finetune.dataset_loader",
        "finetune.train_unsloth",
        "finetune.train_hf",
        "finetune.merge",
        "finetune.export_gguf",
        "finetune.marketplace",
        "cli",
        "cli.theme",
        "cli.render",
        "cli.repl",
        "cli.commands",
        "cli.app",
        "core",
        "core.config",
        "core.inference",
        "core.language",
        "core.ollama_client",
        "core.backend_factory",
        "core.llama_cpp_backend",
        "core.model_manager",
        "core.model_runtime",
        "core.update",
        "web.search_backend",
        "orchestrator",
        "orchestrator.assistant",
        "orchestrator.agent",
        "orchestrator.router",
        "orchestrator.strategy",
        "orchestrator.prompt_builder",
        "orchestrator.git_helper",
        "rag",
        "rag.service",
        "rag.chunker",
        "rag.embedder",
        "rag.indexer",
        "rag.retriever",
        "rag.store",
        "chromadb",
        "chromadb.api",
        "chromadb.api.client",
        "chromadb.api.rust",
        "chromadb_rust_bindings",
        "chromadb.execution.expression.plan",
        "chromadb.config",
        "chromadb.db",
        "chromadb.db.impl",
        "chromadb.segment",
        "chromadb.segment.impl",
        "chromadb.telemetry",
        "chromadb.telemetry.product",
        "chromadb.telemetry.product.posthog",
        "chromadb.telemetry.product.events",
        "licensing",
        "licensing.models",
        "licensing.verifier",
        "licensing.store",
        "licensing.gate",
        "licensing.fingerprint",
        "cryptography.hazmat.primitives.asymmetric.ed25519",
        "yaml",
        "dotenv",
        "httpx",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "sentence_transformers",
        "torch",
        "flashrank",
        "trafilatura",
        "tree_sitter",
        "duckdb",
        "PyInstaller",
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Fluxion",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon="assets/icon.ico",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="Fluxion",
)
