"""Export merged model to GGUF format for Ollama via llama.cpp.

Usage (in Python 3.11/3.12 venv):
    python -m finetune.export_gguf --model data/merged_model

Prerequisites:
    1. Clone llama.cpp:  git clone https://github.com/ggerganov/llama.cpp
    2. Build:            cd llama.cpp && make
    3. Set LLAMA_CPP_DIR env var or use --llama-cpp-dir

After export:
    ollama create fluxion-coder-python -f data/gguf/Modelfile
"""
from __future__ import annotations

import argparse
import logging
import os
import subprocess
import sys
from pathlib import Path

from .qlora_config import QLoRASettings

logger = logging.getLogger(__name__)


def export_gguf(
    model_dir: str,
    settings: QLoRASettings | None = None,
    output_dir: str | None = None,
    llama_cpp_dir: str | None = None,
    quantize: str | None = None,
) -> str:
    """Convert merged model to GGUF and quantize.

    Args:
        model_dir: Path to merged HF model directory.
        settings: QLoRA settings.
        output_dir: Override output directory.
        llama_cpp_dir: Path to llama.cpp build directory.
        quantize: Quantization method (e.g. q4_K_M).

    Returns:
        Path to the final .gguf file.
    """
    settings = settings or QLoRASettings()
    gguf_dir = Path(output_dir or settings.gguf_dir)
    gguf_dir.mkdir(parents=True, exist_ok=True)

    llama_dir = llama_cpp_dir or os.environ.get("LLAMA_CPP_DIR")
    if not llama_dir:
        logger.error(
            "llama.cpp directory not specified. Set LLAMA_CPP_DIR or use --llama-cpp-dir.\n"
            "  git clone https://github.com/ggerganov/llama.cpp\n"
            "  cd llama.cpp && make"
        )
        sys.exit(1)

    convert_script = Path(llama_dir) / "convert_hf_to_gguf.py"
    quantize_bin = Path(llama_dir) / "llama-quantize"

    if not convert_script.exists():
        logger.error("convert script not found: %s", convert_script)
        sys.exit(1)

    model_name = Path(model_dir).name
    f16_gguf = gguf_dir / f"{model_name}.f16.gguf"

    # ── Step 1: Convert HF → GGUF (F16) ──
    logger.info("Converting %s → GGUF (F16)...", model_dir)
    cmd_convert = [
        sys.executable,
        str(convert_script),
        str(model_dir),
        "--outtype", "f16",
        "--outfile", str(f16_gguf),
    ]
    result = subprocess.run(cmd_convert, capture_output=True, text=True)
    if result.returncode != 0:
        logger.error("Conversion failed: %s", result.stderr)
        sys.exit(1)

    # ── Step 2: Quantize ──
    quant = quantize or settings.gguf_quantize
    final_gguf = gguf_dir / f"{model_name}.{quant}.gguf"

    if quantize_bin.exists():
        logger.info("Quantizing → %s ...", quant)
        cmd_quant = [
            str(quantize_bin),
            str(f16_gguf),
            str(final_gguf),
            quant,
        ]
        result = subprocess.run(cmd_quant, capture_output=True, text=True)
        if result.returncode != 0:
            logger.error("Quantization failed: %s", result.stderr)
            sys.exit(1)

        logger.info("Removing F16 intermediate file...")
        f16_gguf.unlink(missing_ok=True)
    else:
        logger.warning("llama-quantize not found, skipping quantization. Using F16.")
        final_gguf = f16_gguf

    # ── Step 3: Generate Modelfile for Ollama ──
    modelfile_path = gguf_dir / "Modelfile"
    modelfile_content = _generate_modelfile(final_gguf.name, settings)
    modelfile_path.write_text(modelfile_content, encoding="utf-8")

    logger.info("GGUF exported: %s", final_gguf)
    logger.info("Modelfile: %s", modelfile_path)
    logger.info(
        "Create Ollama model:\n"
        "  cd %s\n"
        "  ollama create %s -f Modelfile",
        gguf_dir, settings.ollama_model_name,
    )

    return str(final_gguf)


def _generate_modelfile(gguf_name: str, settings: QLoRASettings) -> str:
    """Generate an Ollama Modelfile for the fine-tuned model."""
    return f"""# Modelfile for {settings.ollama_model_name}
# Generated by Fluxion data pipeline

FROM ./{gguf_name}

PARAMETER temperature {0.2}
PARAMETER top_p {0.9}
PARAMETER num_ctx {32768}
PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"
PARAMETER stop "<|endoftext|>"

TEMPLATE \"\"\"{{{{- if .System }}}}<|im_start|>system
{{{{ .System }}}}<|im_end|>
{{{{- end }}}}
<|im_start|>user
{{{{ .Prompt }}}}<|im_end|>
<|im_start|>assistant
\"\"\"

SYSTEM \"\"\"You are Fluxion, an expert Python programming assistant. Give concise, correct answers with runnable code examples.\"\"\"
"""


def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )
    parser = argparse.ArgumentParser(description="Export merged model to GGUF")
    parser.add_argument("--model", required=True, help="Path to merged HF model")
    parser.add_argument("--output", default=None, help="Output directory for GGUF")
    parser.add_argument("--llama-cpp-dir", default=None, help="Path to llama.cpp")
    parser.add_argument("--quantize", default=None, help="Quantization method (e.g. q4_K_M)")
    args = parser.parse_args()

    export_gguf(
        model_dir=args.model,
        output_dir=args.output,
        llama_cpp_dir=args.llama_cpp_dir,
        quantize=args.quantize,
    )


if __name__ == "__main__":
    main()
